language: node.js
node_js:
  - "10"
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - npm run build 
  - npm run test --prefix client